<%@ Page Language="vb" AutoEventWireup="false" MasterPageFile="~/online.Master" CodeBehind="internetapplication.aspx.vb" Inherits="Onliietest.internetapplication" 
    title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <table class="style1">
        <tr>
            <td style="color: #993366; font-size: xx-large">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
                <span style="color: #CC33FF"><b>INTERNET APPLICATION&nbsp;</b></span></td>
        </tr>
        <tr>
            <td>
                <p>
                    <span style="font-size: large; color: #0099CC">The Internet has many important applications. Of the various services available 
                    via the Internet, the three most important are e-mail, web browsing, and 
                    peer-to-peer services . E-mail, also known as electronic mail, is the most 
                    widely used and successful of Internet applications. Web browsing is the 
                    application that had the greatest influence in dramatic expansion of the 
                    Internet and its use during the 1990s. Peer-to-peer networking is the newest of 
                    these three Internet applications, and also the most controversial, because its 
                    uses have created problems related to the access and use of copyrighted 
                    materials.</span></p>
                <h2 style="font-size: large; color: #0099CC">
                    <span style="font-weight: normal">E-Mail</span></h2>
                <p>
                    <span style="font-size: large; color: #0099CC">Whether judged by volume, popularity, or impact, e-mail has been and continues 
                    to be the principal Internet application. This is despite the fact that the 
                    underlying technologies have not been altered significantly since the early 
                    1980s. In recent years, the continuing rapid growth in the use and volume of 
                    e-mail has been fueled by two factors. The first is the increasing numbers of 
                    Internet Service Providers (ISPs) offering this service, and secondly, 
                    because the number of physical devices capable of supporting e-mail has grown to 
                    include highly portable devices such as personal digital assistants (PDAs) 
                    and cellular telephones.</span></p>
                <p>
                    <span style="font-size: large; color: #0099CC">The volume of e-mail also continues to increase because there are more users, 
                    and because users now have the ability to attach documents of various types to 
                    e-mail messages. While this has long been possible, the formulation of 
                    Multipurpose Internet Mail Extensions (MIME) and its adoption by software 
                    developers has made it much easier to send and receive attachments, including 
                    word-processed documents, spreadsheets, and graphics. The result is that the 
                    volume of traffic generated by e-mail, as measured in terms of the number of 
                    data packets moving across the network, has increased dramatically in 
                    recent years, contributing significantly to network congestion.</span></p>
                <p style="font-size: large; color: #0099CC">
                    E-mail has become an important part of personal communications for hundreds of 
                    millions of people, many of whom have replaced it for letters or telephone 
                    calls. In business, e-mail has become an important advertising medium, 
                    particularly in instances where the demand for products and services is time 
                    sensitive. For example, tickets for an upcoming sporting event are marketed by 
                    sending fans an e-mail message with information about availability and prices of 
                    the tickets. In addition, e-mail serves, less obviously, as the basis for some 
                    of the more important collaborative applications that have been developed, most 
                    notably Lotus Notes.</p>
                <h2 style="font-size: large; color: #0099CC">
                    <span style="font-weight: normal">Web Browsing</span></h2>
                <p style="font-size: large; color: #0099CC">
                    The web browser is another Internet application of critical importance. Unlike 
                    e-mail, which was developed and then standardized in the early, noncommercial 
                    days of the Internet, the web browser was developed in a highly commercialized 
                    environment dominated by such corporations as Microsoft and Netscape, and 
                    heavily influenced by the World Wide Web Consortium (W3C). While Microsoft and 
                    Netscape have played the most obvious parts in the development of the web 
                    browser, particularly from the public perspective, the highly influential role 
                    of the W3C may be the most significant in the long term.</p>
                <p>
                    <span style="font-size: large; color: #0099CC">Founded in 1994 by Tim Berners-Lee, the original architect of the web, the goal 
                    of the W3C has been to develop interoperable technologies that lead the web to 
                    its full potential as a forum for communication, collaboration, and commerce. 
                    What the W3C has been able to do successfully is to develop and promote the 
                    adoption of new, open standards for web-based documents. These standards have 
                    been designed to make web documents more expressive (Cascading Stylesheets), to 
                    provide standardized labeling so that users have a more explicit sense of the 
                    content of documents (Platform for Internet Content Selection, or PICS), and to 
                    create the basis for more interactive designs (the Extensible Markup Language, 
                    or XML ). Looking ahead, a principal goal of the W3C is to develop 
                    capabilities that are in accordance with Berners-Lee&#39;s belief that the web 
                    should be a highly collaborative information space.</span></p>
                <p style="font-size: large; color: #0099CC">
                    Microsoft and Netscape dominate the market for web browsers, with Microsoft&#39;s 
                    Internet Explorer holding about three-quarters of the market, and Netscape 
                    holding all but a small fraction of the balance. During the first few years of 
                    web growth, the competition between Microsoft and Netscape for the browser 
                    market was fierce, and both companies invested heavily in the development of 
                    their respective browsers. Changes in business conditions toward the end of the 
                    1990s and growing interest in new models of networked information exchange 
                    caused each company to focus less intensely on the development of web browsers, 
                    resulting in a marked slowing of their development and an increasing disparity 
                    between the standards being developed by W3C and the support offered by Internet 
                    Explorer or Netscape Navigator.</p>
                <p>
                    <span style="font-size: large; color: #0099CC">Now, the future of the web browser may be short-lived, as standards developers 
                    and programmers elaborate the basis for network-aware applications that 
                    eliminate the need for the all-purpose browser. It is expected that as 
                    protocols such as XML and the Simple Object Access Protocol (SOAP) grow more 
                    sophisticated in design and functionality, an end user&#39;s interactions with the 
                    web will be framed largely by desktop applications called in the services of 
                    specific types of documents called from remote sources.</span></p>
                <p style="font-size: large; color: #0099CC">
                    The open source model has important implications for the future development of 
                    web browsers. Because open source versions of Netscape have been developed on a 
                    modular basis, and because the source code is available with few constraints on 
                    its use, new or improved services can be added quickly and with relative ease. 
                    In addition, open source development has accelerated efforts to integrate web 
                    browsers and file managers. These efforts, which are aimed at reducing 
                    functional distinctions between local and network-accessible resources, may be 
                    viewed as an important element in the development of the &quot;seamless&quot; information 
                    space that Berners-Lee envisions for the future of the web</p>
                                <h2 style="font-size: large; color: #0099CC">
                                    <span style="font-weight: normal">Peer-To-Peer Computing</span></h2>
                                <p style="font-size: large; color: #0099CC">
                                    One of the fastest growing, most controversial, and potentially most important 
                                    areas of Internet applications is peer-to-peer (P2P) networking. Peer-to-peer 
                                    networking is based on the sharing of physical resources, such as hard drives, 
                                    processing cycles, and individual files among computers and other intelligent 
                                    devices. Unlike client-server networking, where some computers are dedicated to 
                                    serving other computers, each computer in peer-to-peer networking has equivalent 
                                    capabilities and responsibilities.</p>
            </td>
        </tr>
    </table>
</asp:Content>
